# Generated by Django 3.0.8 on 2020-10-27 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201027_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
