# Generated by Django 3.0.8 on 2020-12-11 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponName', models.CharField(max_length=10)),
                ('discounPercentage', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('discountInfo', models.CharField(max_length=50)),
                ('expiryDate', models.DateTimeField()),
            ],
        ),
    ]
