# Generated by Django 3.0.8 on 2020-12-14 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdetails',
            name='discountCap',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
