# Generated by Django 3.0.8 on 2020-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
