# Generated by Django 3.0.8 on 2020-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_auto_20201104_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='product_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
