# Generated by Django 3.0.8 on 2020-11-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_menuitems_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='product_name',
        ),
    ]
