# Generated by Django 3.0.8 on 2020-11-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0004_remove_menuitems_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='Veg',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
