# Generated by Django 3.0.8 on 2020-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0005_auto_20201120_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(blank=True, default='Recommended', max_length=50),
        ),
    ]
