# Generated by Django 3.0.8 on 2020-11-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0006_auto_20201125_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='Veg',
            new_name='veg',
        ),
    ]
